# .github/workflows/gitstream.yml
name: gitStream
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  run-gitstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history (base + head)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitStream (v2 pinned)
        uses: linear-b/gitstream-github-action@2.0.168
